 <script>
        try {
            willExcept.byebye();
        } catch (exception) {
            alert('예외가 발생했습니다.');
        } finally {
            alert('예외 발생 가능 부분을 통과했습니다.');
        }
    </script>

================================================================================

<script>
        try {
            var array = new Array(999999999999);
        } catch (exception) {
            var output = '';
            for (var i in exception) {
                output += i + ': ' + exception[i] + '\n';
            }
            alert(output);
        }
    </script> 
